# Generated by Django 3.2.3 on 2021-07-01 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(default='', max_length=12)),
                ('Nombre', models.CharField(default='', max_length=20)),
                ('Apellido', models.CharField(default='', max_length=20)),
                ('Gmail', models.CharField(default='', max_length=100)),
                ('telefono', models.CharField(default='', max_length=12)),
                ('contraseña', models.CharField(default='', max_length=20)),
                ('fecha_creacion', models.DateTimeField(verbose_name='Fecha de creación')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_de_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=100)),
                ('fecha_creacion', models.DateTimeField(verbose_name='Fecha de creación')),
                ('precio', models.IntegerField(default=0)),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasteleria.tipo_de_producto')),
            ],
        ),
    ]
