# Generated by Django 3.2.3 on 2021-07-01 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasteleria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dato',
            name='contraseña',
        ),
    ]
