# Generated by Django 3.2.3 on 2021-07-03 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasteleria', '0006_alter_dato_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Compra',
        ),
    ]
